apps/foods/urls.py
from django.urls import path
from . import views

app_name = 'foods'

urlpatterns =[
    path('detail/', views.food_detail, name='detail')
]

apps/lucks/urls.py
from django.urls import path
from . import views

app_name = 'lucks'

urlpatterns =[
    path('detail/', views.luck_detail, name='detail')
]

apps/soccers/urls.py
from django.urls import path
from . import views

app_name = 'soccers'

urlpatterns =[
    path('detail/', views.soccer_detail, name='detail')
]

apps/weathers/urls.py
from django.urls import path
from . import views

app_name = 'weathers'

urlpatterns =[
    path('detail/', views.weather_detail, name='detail')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.recommends import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.recommends.urls')),
    path('', include('users.urls') ),
    path('foods/', include('apps.foods.urls') ),
    path('lucks/', include('apps.lucks.urls') ),
    path('weathers/', include('apps.weathers.urls') ),
    path('soccers/', include('apps.soccers.urls') ),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('', main, name='main'),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('detail/', user_detail, name='user_detail'),
    path('delete/', user_delete, name='user_delete'),
    path('update/', user_update, name='user_update'),
    path('logout/', logout, name='logout'),
]

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport", content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!--apps CSS-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <script src="https://kit.fontawesome.com/5ca80322e1.js" crossorigin="anonymous"></script>
    {%block head%}
    
    {%endblock%}
</head>
<body>
    <header class="header">
        <a href = "/"><div class="logo"><img src="{% static 'logo.jpg' %}"></div></a>
        <nav class="base_nav">
            <ul>
                <li>
                    {% if user.is_authenticated %}
                    <a class="" href="{% url 'users:logout'%}">로그아웃</a>
                    {% else %}
                    <a class="" href="{% url 'users:login'%}">로그인</a>
                    <a class="" href="{% url 'users:signup'%}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </header>
    <div class="center">
        <main class="main_container">
            {%block content%}
            
            {%endblock%}
        </main>
    </div>
    <footer>

    </footer>
</body>
{%block script%}
{%endblock%}
</html>

templates/main.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<title>더 나은 오늘을 위해</title>
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %} 
{% block content %}
<div class="main_box">
    <div class="left">

    </div>
    <div class="right">
        <ul class="col Today">
            <li class="col">
                {% if user.is_authenticated %}
                <a class="" href="{% url 'foods:detail'%}"><i class="fa-solid fa-bowl-food"></i> 오늘의 음식 <i class="fa-solid fa-bowl-food"></i> </a>
                {% for food in user.food.all %}
                    <span>{{food.names}}</span>
                {% endfor %}
                {% else %}
                <span class="">오늘의 음식</span>
                
                <a class="" href="{% url 'users:login'%}">로그인이 필요한 서비스입니다</a>
                {% endif %} 
            </li>
            <li class="col">
                <a class="" href="{% url 'soccers:detail'%}"><i class="fa-solid fa-futbol"></i> 오늘의 해외축구 일정 <i class="fa-solid fa-futbol"></i></a>
            </li>
            
            <li class="col">
                {% if user.is_authenticated %}
                <a class="" href="{% url 'lucks:detail'%}"><i class="fa-solid fa-clover"></i> 오늘의 운세 <i class="fa-solid fa-clover"></i> </a>
                {% for luck in user.luck.all %}
                    <span>{{luck.names}}</span>
                {% endfor %}
                {% else %}
                <span class="">오늘의 운세</span>
                
                <a class="" href="{% url 'users:login'%}">로그인이 필요한 서비스입니다</a>
                {% endif %} 
            </li>

            <li class="col">
                <!--{% if user.is_authenticated %}-->
                <a class="" href="{% url 'weathers:detail'%}"><i class="fa-solid fa-clover"></i> 오늘의 날씨 <i class="fa-solid fa-clover"></i> </a>
                {% for weather in user.weather.all %}
                    <span>@현재 시간 기준 5시간 동안의 날씨를 제공합니다@</span>
                <!--{% endfor %}
                {% else %}
                <span class="">오늘의 날씨</span>
                
                <a class="" href="{% url 'users:login'%}">로그인이 필요한 서비스입니다</a>
                {% endif %} -->
            </li>
        </ul>
    </div>
</div>
{% endblock %}