config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.recommends import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.recommends.urls')),
    path('', include('users.urls') ),
    path('foods/', include('apps.foods.urls') ),
    path('lucks/', include('apps.lucks.urls') ),
    path('weathers/', include('apps.weathers.urls') ),
    path('soccers/', include('apps.soccers.urls') ),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('', main, name='main'),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('detail/', user_detail, name='user_detail'),
    path('delete/', user_delete, name='user_delete'),
    path('update/', user_update, name='user_update'),
    path('logout/', logout, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    name = models.CharField(max_length = 20, default='unknown')
    birth = models.DateField()
    def __str__ (self):
        return self.name

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from .models import User

class userCreate(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'name', 'birth')
    
    def __init__(self, *args, **kwargs):
        super(userCreate, self).__init__(*args, **kwargs)
        self.fields['username'].label = '아이디'
        self.fields['name'].label = '유저명'
        self.fields['birth'].label = '생일'

class userChange(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('username', 'name')

class CustomUserChangeForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ['username', 'name']

apps/users/views.py
from django.db import models

# Create your models here.
from django.shortcuts import render, redirect
from django.contrib import auth
from .forms import CustomUserChangeForm
from .forms import userCreate
from django.contrib.auth.forms import AuthenticationForm
from .models import *
# Create your views here.

# 유저 프로필 페이지
def user_detail(request):
    user = request.user
    if user.is_authenticated:
        ctx = {
            'user' : user,
        }
        return render(request, 'users/user_detail.html', ctx)
    return redirect('users:login') #users:login = 로그인 페이지


# 유저 계정 탈퇴 페이지
def user_delete(request):
    user = request.user
    if user.is_authenticated:
        user.delete()
        auth.logout(request)
    return redirect('users:main') #users:main = 로그인 하기 전에 보여지는 main 페이지


# 유저 프로필 수정 페이지
def user_update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:user_detail')
    form = CustomUserChangeForm(instance=request.user)
    ctx = {
        'form' : form,
    }
    return render(request, 'users/user_update.html', ctx)

# 로그아웃
def user_logout(request):
    auth.logout(request)
    return redirect('users:main')


def signup(request):
    if request.method == 'POST':
        form = userCreate(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('users:main')
    else:
        form = userCreate()

    ctx = {'form': form}
    return render(request, 'users/user_signup.html', ctx)


def login (request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('users:main')
        else:
            ctx = {
                'form' : form
            }
            return render(request, 'users/user_login.html', ctx)
    else:
        form = AuthenticationForm()
        ctx = {
            
            'form': form,
        }
        return render(request, 'users/user_login.html', ctx)
    
def logout(request):
    auth.logout(request)
    return redirect('users:main')

def main (request):
    users = User.objects.all()
    ctx = {
        'users' : users
    }
    return render(request, 'users/user_main.html', ctx)

users/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from .forms import CustomUserChangeForm
from .forms import userCreate
from django.contrib.auth.forms import AuthenticationForm
from .models import *

def main(request):
    if request.user.is_anonymous:
        return render(request, 'main.html')
    return render(request, 'main.html')

# 유저 프로필 페이지
def user_detail(request):
    user = request.user
    if user.is_authenticated:
        ctx = {
            'user' : user,
        }
        return render(request, 'users/user_detail.html', ctx)
    return redirect('users:login') #users:login = 로그인 페이지


# 유저 계정 탈퇴 페이지
def user_delete(request):
    user = request.user
    if user.is_authenticated:
        user.delete()
        auth.logout(request)
    return redirect('users:main') #users:main = 로그인 하기 전에 보여지는 main 페이지


# 유저 프로필 수정 페이지
def user_update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:user_detail')
    form = CustomUserChangeForm(instance=request.user)
    ctx = {
        'form' : form,
    }
    return render(request, 'users/user_update.html', ctx)

# 로그아웃
def user_logout(request):
    auth.logout(request)
    return redirect('users:main')


def signup(request):
    if request.method == 'POST':
        form = userCreate(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('users:main')
    else:
        form = userCreate()

    ctx = {'form': form}
    return render(request, 'users/user_signup.html', ctx)


def login (request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('users:main')
        else:
            ctx = {
                'form' : form
            }
            return render(request, 'users/user_login.html', ctx)
    else:
        form = AuthenticationForm()
        ctx = {
            
            'form': form,
        }
        return render(request, 'users/user_login.html', ctx)
    
def logout(request):
    auth.logout(request)
    return redirect('users:main')

templates/users/user_detail.html
{% extends "base.html" %}
{% block head %}
    <title>user detail</title>
    <style>
        .btns{
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .btn-danger {
            background-color: #f44336; /* '탈퇴하기' 버튼 배경색 */
        }
        .btn:hover {
            opacity: 0.9; /* 버튼 호버 효과 */
        }
    </style>
{% endblock %}

{% block content %}
<div class="box">
    <h1>회원정보</h1>
    <p class="user-name"><strong>아이디:</strong> {{ user.username }}</p>
    <p class="name"><strong>이름:</strong> {{ user.name }}</p>
    <p class="score"><strong>생일</strong> {{ user.birth }}점</p>
    <div class="btns">
        <a href="{% url 'users:user_update' %}" class="btn">프로필 수정하기</a>
        <form action="{% url 'users:user_delete' %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">탈퇴하기</button>
        </form>
    </div>
</div>
{% endblock %}

templates/users/user_login.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<title>login</title>

{% endblock %} {% block content %}
<div class="box">
  <h1>로그인</h1>
  <form method="POST" action="{% url 'users:login' %}">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" class="btn">로그인</button>
  </form>
  {% comment %} 
  <a href="{% url 'social:begin' 'naver' %}" class="naver-login-button">
    <img src="{%static 'image/naver.ico'%}"/>
  </a>
  <a href="{% provider_login_url 'google' %}">
    <img src="{%static 'image/google.png'%}" style="width: 32px;"/>
  </a>
  <a href="{% provider_login_url 'kakao' %}">
    <img src="{%static 'image/kakao.png'%}" style="width: 32px;"/>
  </a>
  {% endcomment %}
</div>
{% endblock %}

templates/users/user_signup.html
{% extends "base.html" %}

{% block head %}
<title>login</title>
{% endblock %}

{% block content %}
<div class="box">
  <h1>회원가입</h1>
  <div class="signup-content">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn">회원가입</button>
    </form>
  </div>
</div>
{% endblock %}

templates/users/user_update.html
{% extends "base.html" %}
{% block head %}
    <title>user update</title>
    <style>
        .update-form {
            width: 40%;
            margin: 60px auto;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            text-align: center;
        }

        .update-form form{
            text-align: left;
        }

        .update-form button {
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }
        .update-form button:hover {
            opacity: 0.9;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="update-form">
        <h1>회원정보 수정</h1>
        <form method="post" action="{% url 'users:user_update' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">정보 수정하기</button>
        </form>
    </div>
{% endblock %}